version: "3"
services:

  mysql:
    build: ./docker/mysql
    env_file:
      - ./docker/mysql/.env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  nginx:
    build: ./docker/nginx
    env_file:
      - ./docker/nginx/.env
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

  php-fpm:
    build: ./docker/php-fpm
    env_file:
      - ./docker/php-fpm/.env
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    depends_on:
      - mysql
    networks:
      - backend

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
